# Generated by Django 2.2.1 on 2019-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
