# Generated by Django 2.2.1 on 2019-05-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
