# Generated by Django 2.2.1 on 2019-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190528_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
