# Generated by Django 2.2.1 on 2019-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190529_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
