# Generated by Django 2.2.1 on 2019-05-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_food_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='username',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
