# Generated by Django 2.2.1 on 2019-06-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190601_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
