# Generated by Django 2.2.1 on 2019-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommend',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
