# Generated by Django 2.2.1 on 2019-06-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190604_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
