# Generated by Django 2.2.1 on 2019-06-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='foodname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
